<?php
const IMPROVEMENT_GOAL_QUALITY = 1;
const IMPROVEMENT_GOAL_SAFETY = 2;
const IMPROVEMENT_GOAL_LABOR = 3;
const IMPROVEMENT_GOAL_MOVEMENT = 4;
const IMPROVEMENT_GOAL_CULTURE = 5;
const IMPROVEMENT_GOAL_OTHER = 100;
const IMPROVEMENT_GOALS = array(IMPROVEMENT_GOAL_QUALITY, IMPROVEMENT_GOAL_SAFETY, IMPROVEMENT_GOAL_LABOR, IMPROVEMENT_GOAL_MOVEMENT, IMPROVEMENT_GOAL_CULTURE, IMPROVEMENT_GOAL_OTHER);
const IMPROVEMENT_GOALS_NAMES = array(IMPROVEMENT_GOAL_QUALITY => "Качество", IMPROVEMENT_GOAL_SAFETY => "Безопасность", IMPROVEMENT_GOAL_LABOR => "Снижение трудоёмкости", IMPROVEMENT_GOAL_MOVEMENT => "Сокращение лишних движений", IMPROVEMENT_GOAL_CULTURE => "Повышение культуры рабочего места", IMPROVEMENT_GOAL_OTHER => "Прочее");
?>